from django.urls import path
from . import views
from .views import (
	TopicsDetailView,
    RemarksDetailView,
    HomeworkDetailView,
    SubmissionDetailView,
    ProjectDetailView,
    ReminderDetailView,
    UsersDetailView,
    PostDetailView,
    TweetDetailView,
    TopicCreateView,
    RemarkCreateView,
    HomeworkCreateView,
    SubmissionCreateView,
    ProjectCreateView,
    ReminderCreateView,
    TimeTableCreateView,
    PostCreateView,
    TweetCreateView
	)

urlpatterns = [
	path('home/', views.home, name='home'),
	path('topics/', views.topic, name='student-topics'),
	path('remarks/', views.remarks, name='student-remarks'),
	path('homeworks/', views.homeworks, name='student-homeworks'),
	path('submissions/', views.submissions, name='student-submissions'),
	path('projects/', views.projects, name='student-projects'),
	path('reminders/', views.reminders, name='student-reminders'),
	path('timetable/', views.timetable, name='student-timetable'),
	path('myclass/', views.myclass, name='teacher-myclass'),
	path('teachers/', views.teachers, name='principal-teachers'),
	path('topics/<int:pk>/', TopicsDetailView.as_view(), name='topics-detail'),
	path('remarks/<int:pk>/', RemarksDetailView.as_view(), name='remarks-detail'),
	path('homeworks/<int:pk>/', HomeworkDetailView.as_view(), name='homeworks-detail'),
	path('submissions/<int:pk>/', SubmissionDetailView.as_view(), name='submissions-detail'),
	path('projects/<int:pk>/', ProjectDetailView.as_view(), name='projects-detail'),
	path('reminders/<int:pk>/', ReminderDetailView.as_view(), name='reminders-detail'),
	path('teachers/<int:pk>/', UsersDetailView.as_view(), name='users-detail'),
	path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
	path('tweet/<int:pk>/', TweetDetailView.as_view(), name='tweet-detail'),
	path('works/', views.works, name='works'),
	path('topics/new/', TopicCreateView.as_view(), name='topics-create'),
	path('remarks/new/', RemarkCreateView.as_view(), name='remarks-create'),
	path('homeworks/new/', HomeworkCreateView.as_view(), name='homeworks-create'),
	path('submissions/new/', SubmissionCreateView.as_view(), name='submissions-create'),
	path('projects/new/', ProjectCreateView.as_view(), name='projects-create'),
	path('reminders/new/', ReminderCreateView.as_view(), name='reminders-create'),
	path('timetable/new/', TimeTableCreateView.as_view(), name='timetable-create'),
	path('mytopics/', views.mytopics, name='teacher-mytopics'),
	path('myremarks/', views.myremarks, name='teacher-myremarks'),
	path('myhomeworks/', views.myhomeworks, name='teacher-myhomeworks'),
	path('myreminders/', views.myreminders, name='teacher-myreminders'),
	path('mysubmissions/', views.mysubmissions, name='teacher-mysubmissions'),
	path('myprojects/', views.myprojects, name='teacher-myprojects'),
	path('post/new/', PostCreateView.as_view(), name='post-create'),
	path('tweet/new/', TweetCreateView.as_view(), name='tweet-create'),
]